export { default as LoadingScreen } from './loading-screen/loading-screen';
export { default as ContactForm } from './contact-form/contact-form';
export { default as UnderConstructionPopup } from './under-construction-popup';
export { default as BlogsCard } from './blogs-card/blogs-card';
export { default as DestinationsCard } from './destinations-card/destinations-card'
export { default as NavigationDots } from './navigation-dots';
export { default as ScrollToTop } from './scroll-to-top';
export { default as PackagesCard } from './packages-card/packages-card';
export { default as TestimonialsBox } from './testimonials-box/testimonials-box';