import React from 'react'
import styles from './page.module.scss';
import Link from 'next/link';

type Props = {}

const TermsAndConditionsPage = (props: Props) => {
  return (
    <div className={styles.termsAndConditions__container}>
    <h1 className={styles.heading}>Terms and conditions</h1>
    <div className={styles.summary}>
      <p>
        This legal contract between you and EventifyConnect (&quot;The
        EventifyConnect&quot;) which govern your use of{" "}
        <a href="https://eventifyconnect.netlify.app">
          www.eventifyconnect.com
        </a>{" "}
        (the &quot;Website&quot;) and EventifyConnect&apos;s online listing
        and booking platform for event locations (&quot;Halls&quot;) and
        related services available via the Website.
      </p>
      <br />
      <p>
        This document is an electronic record in terms of Information
        Technology Act, 2000 and rules made there under as applicable and the
        amended provisions pertaining to electronic records in various
        statutes as amended by the Information Technology Act, 2000. This
        electronic record is generated by a computer system and does not
        require any physical or digital signatures.
      </p>
      <br />
      <p>
        This document is published in accordance with the provisions of Rule 3
        (1) of the Information Technology (Intermediaries guidelines) Rules,
        2011 that require publishing the rules and regulations, privacy policy
        and Terms of Use for access or usage of{" "}
        <a href="http://eventifyconnect.netlify.app">
          www.eventifyconnect.com
        </a>{" "}
        Website.
      </p>
      <br />
      <p>
        In this document, we refer to our services, technologies and Website
        collectively as the &quot;<strong>Services</strong>&quot;.
        <br />
        For convenience, we also use the following defined terms:
      </p>
      <br />
      <ul className={styles.list}>
        <li>
          &quot;<strong>Listing</strong>&quot; means a Halls that is listed by
          you as Hall Owner for rental purposes via the Services;
        </li>
        <li>
          &quot;<strong>End User</strong>&quot; means a person who wishes to
          hire a halls as contemplated herein, as described under
          &quot;Creating an EventifyConnect Account&quot; below;
        </li>
        <li>
          &quot;<strong>Hall Owner</strong>&quot; means an End User of the
          Services who registers with EventifyConnect to create a Listing for
          Halls.
        </li>
      </ul>
      <br />
      <p>
        Unless expressly provided hereunder, the Terms of Use shall apply to
        both the Hall Owner as well as the End User.
        <br />
        By accessing or using our Services, you agree to be bound to all of
        the terms and conditions described in these Terms and Conditions. If
        you do not agree to all of these terms and conditions, do not use our
        Services.
      </p>
      <br />
      <p>
        Please contact us at{" "}
        <a href="mailto:samadhan.ranpise@gmail.com">
          info@eventifyconnect.com
        </a>{" "}
        for any questions regarding these Terms and Conditions.
      </p>
      <br />
      <p className={styles.highlight}>
        THE SERVICES COMPRISE AN ONLINE PLATFORM THROUGH WHICH HALL OWNERS MAY
        LIST HALLS AND END USERS MAY CHOOSE AND BOOK THE HALLS OF THEIR
        CHOICE. YOU UNDERSTAND AND AGREE THAT EVENTIFYCONNECT&apos;S SERVICES
        BRING HALL OWNERS AND END USERS TOGETHER; HOWEVER, EVENTIFYCONNECT IS
        NOT A PARTY TO ANY AGREEMENTS ENTERED INTO BETWEEN HALL OWNERS AND END
        USERS. AS A RESULT, EVENTIFYCONNECT HAS NO CONTROL OVER THE CONDUCT OF
        HALL OWNERS OR END USERS VIA THE SERVICES OR HALLS FEATURED ON THE
        SERVICES, AND DISCLAIMS ALL LIABILITY IN THIS REGARD.
      </p>
    </div>
    <div className={styles.wrapper}>
      <div className={styles['sub-heading']}>Agreement to these terms of use</div>
      <div className={styles.description}>
        <ol className={styles.list}>
          <li>
            <span>
              BY CLICKING ON THE &quot;I HAVE READ AND AGREE TO THE TERMS OF
              SERVICE&quot; BUTTON OR BY ACCESSING OR USING THE SERVICES, YOU
              AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS WHETHER OR NOT
              YOU HAVE REGISTERED WITH THE SERVICES. IF YOU DON&apos;T AGREE
              TO THESE TERMS AND THE PRIVACY POLICY THEN YOU HAVE NO RIGHT OR
              AUTHORIZATION TO USE THE SERVICes.
            </span>
            &nbsp;If you agree to these terms on behalf of a company or other
            legal entity, you represent and warrant that you have the
            authority to bind that company or other legal entity to these
            Terms and Conditions and, in that case, &quot;you&quot; and
            &quot;your&quot; will refer and apply to that company or other
            legal entity.
          </li>
          <br />
          <li>
            At some point, different areas of the Services and your access to
            or use of certain Services or Content (defined below) may have
            different terms and conditions or may require you to agree with
            and accept additional terms and conditions. If there is a conflict
            between these Terms and Conditions and terms and conditions posted
            for a specific area of the Services or Website Content (defined
            below), the latter terms and conditions will take precedence with
            respect to your use of or access to that area of the Services or
            Website Content.
          </li>
        </ol>
      </div>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>CHANGES IN THE TERMS AND CONDITIONS</h2>
      <p className={styles.description}>
        EventifyConnect, may, at its sole discretion, modify these Terms and
        Conditions, at any time and without prior notice. If we do so, we will
        let you know either by posting the modified Terms of Use on the
        Website or through other communications. It is important that you
        review the revised Terms and Conditions as and when posted in the Web
        site. If you continue to use the Services after we post modified Terms
        and Conditions you are indicating to us that you agree to be bound by
        the revised Terms and Conditions. Because our Services are evolving,
        if the revised Terms and Conditions are not acceptable to you, you
        must immediately stop using the Services. We may change or discontinue
        all or part of the Services, at any time, without notice to you, at
        our sole discretion. We may also create limits related to use of the
        Service or parts of the Service, without notice or liability to you.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>HOW EVENTIFYCONNECT WORKS</h2>
      <p>
        The Services are intended solely for persons who are 18 or older. Any
        access to or use of the Services by anyone under 18 is expressly
        prohibited. By accessing or using the Services you represent and
        warrant that you are 18 or older.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>
        CREATING AN EVENTIFYCONNECT ACCOUNT OR BOOKING
      </h2>
      <h3 className={styles['sub-sub-heading']}>As an End User:</h3>
      <p className={styles.description}>
        When creating an Account or Booking, you will be required to provide
        certain information and you may establish a username and a password.
        You agree to provide accurate, current and complete information during
        the registration process and to update such information to keep it
        accurate, current and complete. You shall register directly through
        the Website. We reserve the right to suspend or terminate your
        Account/Booking if any information provided during the registration
        process or thereafter proves to be inaccurate, false or misleading, or
        to reclaim any username that you create through the Services that
        violates these Terms and Condition. You are responsible for
        maintaining the confidentiality of your password and Account/Event,
        and agree to notify us if your password is lost, stolen, or disclosed
        to an unauthorized third party, or otherwise may have been
        compromised. You are responsible for activities that occur under your
        Account.
      </p>
      <h3 className={styles['sub-sub-heading']}>As a Hall Owner :</h3>
      <p className={styles.description}>
        When creating an Account or Listing your Hall, you will be required to
        provide certain information and you may establish a username and a
        password. You agree to provide accurate, current and complete
        information during the registration process and to update such
        information to keep it accurate, current and complete. You shall
        register directly through the Website after paying the necessary fee
        as agreed with EventifyConnect in terms of the Listing agreement. We
        reserve the right to suspend or terminate your Account if any
        information provided during the registration process or thereafter
        proves to be inaccurate, false or misleading, or to reclaim any
        username that you create through the Services that violates these
        Terms and Condition. You are responsible for maintaining the
        confidentiality of your password and Account, and agree to notify us
        if your password is lost, stolen, or disclosed to an unauthorized
        third party, or otherwise may have been compromised. You are
        responsible for activities that occur under your Account.(d)
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>BOOKINGS AND FINANCIAL TERMS</h2>
      <div className={styles.description}>
        <ol className={styles.list}>
          <li>
            The Hall Owners, not EventifyConnect, are solely responsible for
            fulfilling Hall Visits and bookings, and making available any
            Halls reserved through the Services. It is the Hall Owner and not
            EventifyConnect which determines the Hall booking fees due and
            payable by the End User to the Hall Owner for and related to a
            booking of the Hall and the possible fee range for booking a Hall
            provided in the Listing. Payments are all transacted through Bill
            Desk, PayPal, or other third party payment service methods
            (collectively, &quot;Payment Facilities&quot;) or the
            EventifyConnect payment processing gateway (the
            &quot;Gateway&quot;).
          </li>
          <br />
          <li>
            <strong>Making an Inquiry About a Hall</strong>; Hall Visits. As
            an End User, you can make an inquiry regarding a Hall, request to
            schedule a Hall Visit or request a quote for a Hall Booking Fee
            for a Hall by completing an online inquiry form. Within
            twenty-four (24) business hours of your submission of the form, a
            Hall Owner representative will contact you. Hall Visits are
            subject to the approval of the applicable Hall Owner. You may
            contact a Hall Owner representative should you wish to cancel or
            reschedule a Hall Visit. Should you wish to arrange a booking for
            a Hall after a Hall Visit or otherwise, you agree to make such
            booking via the Services only.
          </li>
          <br />
          <li>
            <strong>Booking a Hall.</strong> After you receive a response to
            your inquiry from Hall Owner, including a quote, and your Hall
            Visit (should you choose to schedule one), you may contact Hall
            Owner to make your booking via the Services. If the Hall you wish
            to book is available on the dates and at the times you request and
            you choose to book the Hall via the Services, EventifyConnect will
            collect the entire Hall Booking Fee, on behalf of the Hall Owner
            at the time of booking
          </li>
          <br />
          <li>
            In connection with the booking of Hall, the End User will be asked
            to provide customary billing information such as name, billing
            address and other relevant information necessary for hiring the
            Hall. Accordingly, The End User agrees to pay Hall owner for any
            bookings made in connection with Account in accordance with these
            Terms and Condition and hereby authorizes the collection of such
            amounts on behalf of the Hall Owner by payment facilities provided
            as part of making the booking, vie the Services. If as an END
            USER, you are directed to Hall owners third party payment
            processor, you may be subject to terms and conditions governing
            use of that third party&apos;s service and that third party&apos;s
            personal information collection practices. Please review such
            terms and conditions and privacy policy before using the services.
          </li>
          <br />
          <li>
            Once EventifyConnect receives confirmation of your booking from
            the applicable Hall Owner, Hall owner will collect the Deposit as
            well as the remaining balance, if applicable, in accordance with
            the these Terms and Condition. All Deposits and remaining balance
            are payable in Indian Rupees (INR) only. Once the booking
            transaction is complete, the END USER will receive a confirmation
            email summarizing your booking and a copy of such confirmation may
            be available for review via your Account, and if not available via
            your account, you can contact us for the same.
          </li>
        </ol>
      </div>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>INSURANCE AND TAXES</h2>
      <p className={styles.description}>
        As a END USER, you agree that it is his/her sole responsibility to
        obtain any insurance as required by law or otherwise related to your
        booking of a Hall or your activities on the Services. EventifyConnect
        does not carry any insurance for bookings made or Hall featured on the
        Services. END USER is also solely responsible for determining any tax
        requirements or obligations you may have related to any bookings made
        via the Services. EventifyConnect cannot and does not offer tax advice
        to any End User.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>BOOKING CHANGES AND CANCELLATIONS</h2>
      <p className={styles.description}>
        Please note that change and cancellation procedures and penalties for
        bookings vary depending on the policies of the applicable Hall Owner.
        Any such cancellation procedures and penalties are those of the Hall
        Owner and not of EventifyConnect, and EventifyConnect has no
        responsibility or liability in this regard. The END USER agrees that
        he/she will accept any terms, conditions and restrictions associated
        with any Hall imposed by the Hall Owner, including, but not limited
        to, any change or cancellation fees. If you have any complaints or
        questions about your experience with a Hall Owner or a Hall, or if you
        wish to cancel a booking made via the Services, please contact the
        applicable Hall Owner directly. Please note that EventifyConnect is
        not responsible for resolving any disputes between End Users and Hall
        Owners or processing any changes to or cancellations of bookings, and
        disclaims any and all liability in this regard. Nothing in this clause
        shall affect the Hall Owners obligation towards the EventifyConnect in
        respect of the payment of the Listing fees in respect of such Hall in
        question.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>PRIVACY POLICY</h2>
      <p className={styles.description}>
        Please refer to our Privacy Policy for information on how we collect,
        use and disclose information from Hall Owners and our End Users. The
        same is available at our site{" "}
        <Link href={"/privacy-policy"} legacyBehavior>
          <a href="">here</a>
        </Link>
        .
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>CONTENT ON EVENTIFYCONNECT</h2>
      <div className={styles.description}>
        <ol className={styles.list}>
          <li>
            <strong>Key Definitions.</strong> &quot;Content&quot; means text,
            graphics, images, music, software, audio, video, information,
            works of authorship or other materials. &quot;EventifyConnect
            Content&quot; means all Content that EventifyConnect makes
            available through the Services, including any Content licensed
            from a third party, but excluding End User Content and Hall Owner
            Content. &quot;End User Content&quot; means all Content that an
            End User posts, uploads, publishes, submits or transmits to be
            made available through the Services. &quot;Website Content&quot;
            means End User Content, Hall Owner Content and EventifyConnect
            Content. &quot;Hall Owner Content&quot; means all Content that a
            Hall Owner posts, uploads, publishes, submits or transmits to be
            made available through the Services, including, but not limited
            to, Listings.
          </li>
          <br />
          <li>
            <strong>EventifyConnect Licenses.</strong> Subject to your
            compliance with the Terms of Use, EventifyConnect grants the End
            User and Hall Owner, a limited, non-exclusive, non-transferable
            license (without the right to sublicense), to access, view,
            download and print any EventifyConnect Content solely for your
            personal and non-commercial purposes. Subject to your compliance
            with the Terms and Conditions, EventifyConnect grants you a
            limited, non- exclusive, non-transferable license (without the
            right to sublicense), to access and view any End User Content and
            Hall Owner Content solely for your personal and internal business
            purposes.
          </li>
          <br />
          <li>
            The Hall owner and the End User will not use, copy, adapt, modify,
            prepare derivative works based upon, distribute, license, sell,
            transfer, publicly display, publicly perform, transmit, stream,
            broadcast or otherwise exploit the Services or Website Content,
            except as expressly permitted in these Terms and Conditions. No
            licenses or rights are granted to you by implication or otherwise
            under any intellectual property rights owned or controlled by
            EventifyConnect or its licensors, except for the licenses and
            rights expressly granted in these Terms and Conditions.
          </li>
          <br />
          <li>
            <strong>End User Content.</strong> EventifyConnect permit End
            Users to post, upload, publish, submit or transmit End User
            Content, including, but not limited to, reviews of Halls. By
            making available any End User Content through the Services, you
            hereby grant to EventifyConnect a worldwide, irrevocable,
            perpetual, non-exclusive, transferable, royalty-free license, with
            the right to sublicense, to use, copy, adapt, modify for
            formatting purposes, distribute, license, transfer, publicly
            display, publicly perform, transmit, stream, broadcast, access,
            view, and otherwise exploit such End User Content in connection
            with the Services, including for promotion of the Services,
            directly or indirectly by intermediaries, and to authorize others
            to do the same.
          </li>
          <br />
          <li>
            The End User agrees to be solely responsible for all the End User
            Content and represents and warrants that: (a) He/she owns the End
            User Content that you provide through the Services, and (b) has
            all rights, licenses, consents and releases, express or implied,
            necessary to use the Services and to grant to EventifyConnect the
            rights in the End User Content you provide via the Services. The
            End User also represents and warrants that your use of, and your
            authorization of EventifyConnect&apos;s use of, the End User
            Content you provide via the Services will not infringe,
            misappropriate or violate a third party&apos;s intellectual
            property rights, or rights of publicity or privacy, or result in
            the violation of any applicable law or regulation.
          </li>
        </ol>
      </div>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>OWNERSHIP</h2>
      <p className={styles.description}>
        Intellectual property laws protect the Services and EventifyConnect
        Content. Except as expressly provided in these Terms, EventifyConnect
        and its licensors own all rights in the Services and EventifyConnect
        Content. EventifyConnect has no ownership rights in End User Content.
        You must not remove, alter or obscure any copyright, trademark,
        service mark or other proprietary rights notices incorporated in or
        accompanying the Services or Website Content. The End User agrees that
        he/she has no right to, or title in or to, any Website Content (except
        for the End User Content that you provide) or any other attributes
        associated with your Account. Likewise, the Hall Owner shall not use
        any content while listing the Hall in the Website that violates the
        intellectual property of EventifyConnect or any Third Party.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>UNDERTAKING</h2>
      <div className={styles.description}>
        <p>
          Our Services may be used and accessed for lawful purposes only. Both
          Hall Owner and the End User undertake and agree not to perform any
          of the following while using or accessing the Services:
        </p>
        <br />
        <ol className={styles.list}>
          <li>
            Post, upload, publish, submit or transmit any Content that: (i)
            infringes, misappropriates or violates a third party&apos;s
            patent, copyright, trademark, trade secret, moral rights or other
            intellectual property rights, or rights of publicity or privacy;
            (ii) violates, or encourages any conduct that would violate, any
            applicable law or regulation or would give rise to civil
            liability; (iii) is fraudulent, false, misleading or deceptive;
            (iv) is defamatory, obscene, pornographic, vulgar or offensive;
            (v) promotes discrimination, bigotry, racism, hatred, harassment
            or harm against any individual or group; (vi) is violent or
            threatening or promotes violence or actions that are threatening
            to any other person; or (vii) promotes illegal or harmful
            activities or substances.
          </li>
          <br />
          <li>
            Use, display, mirror or frame the Website, or any individual
            element within the Services, EventifyConnect&apos;s name, any
            EventifyConnect trademark, logo or other proprietary information,
            or the layout and design of any page or form contained on a page,
            without EventifyConnect&apos;s express written consent;
          </li>
          <br />
          <li>
            Access, tamper with, or use non-public areas of the Services,
            EventifyConnect computer systems, or the technical delivery
            systems of EventifyConnect providers;
          </li>
          <br />
          <li>
            Attempt to probe, scan, or test the vulnerability of any
            EventifyConnect system, network or breach any security or
            authentication measures;
          </li>
          <br />
          <li>
            Avoid, bypass, remove, deactivate, impair, descramble or otherwise
            circumvent any technological measure implemented by
            EventifyConnect or any of EventifyConnect&apos;s providers, or any
            other third party (including another End User) to protect the
            Services or Website Content;
          </li>
          <br />
          <li>
            Attempt to access or search the Website or Website Content or
            download Website Content from the Website through the use of any
            engine, software, tool, agent, device or mechanism (including
            spiders, robots, crawlers, data mining tools or the like) other
            than the software and/or search agents provided by EventifyConnect
            or other generally available third-party web browsers;
          </li>
          <br />
          <li>
            Send any unsolicited or unauthorized advertising, promotional
            materials, email, junk mail, spam, chain letters or other form of
            solicitation;
          </li>
          <br />
          <li>
            Use any meta tags or other hidden text or metadata utilizing a
            EventifyConnect trademark, logo URL or product name without
            EventifyConnect&apos;s express written consent;
          </li>
          <br />
          <li>
            Use the Services or Website Content for any commercial purpose or
            the benefit of any third party or in any manner not permitted by
            the Terms and Conditions;
          </li>
          <br />
          <li>
            Forge any TCP/IP packet header or any part of the header
            information in any email or newsgroup posting, or in any way use
            the Services or Website Content to send altered, deceptive or
            false source-identifying information;
          </li>
          <br />
          <li>
            Attempt to decipher, decompile, disassemble or reverse engineer
            any of the software used to provide the Services or Website
            Content;
          </li>
          <br />
          <li>
            Interfere with, or attempt to interfere with, the access of any
            End User, host or network, including, without limitation, sending
            a virus, overloading, flooding, spamming, or mail- bombing the
            Services; Collect or store any personally identifiable information
            from the Services from other End Users of the Services without
            their express permission;
          </li>
          <br />
          <li>
            Impersonate or misrepresent your affiliation with any person or
            entity;
          </li>
          <br />
          <li>
            Violate any applicable law or regulation; or Encourage or enable
            any other individual to do any of the foregoing.
          </li>
          <br />
          <p>
            EventifyConnect has the right to investigate and prosecute
            violations of any of the above to the fullest extent of the law.
            EventifyConnect may involve and cooperate with law enforcement
            authorities in prosecuting End Users who violate these Terms of
            Use. Both the Hall Owner and the End User acknowledge that
            EventifyConnect has no obligation to monitor their access to or
            use of the Services or Website Content, or to review or edit any
            Website Content, but has the right to do so for the purpose of
            operating the Services, to ensure their compliance with these
            Terms adn Conditions, or to comply with applicable law or the
            order or requirement of a court, administrative agency or other
            governmental body. EventifyConnect reserves the right, at any time
            and without prior notice, to remove or disable access to any
            Content, including, any Website Content for any reason that
            EventifyConnect, at its sole discretion, considers to be
            objectionable, in violation of these Terms and Conditions or
            otherwise harmful to the Services
          </p>
        </ol>
      </div>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>LINKS TO THIRD-PARTY WEBSITES</h2>
      <p className={styles.description}>
        The Services may include links to other Websites and services that are
        not operated by EventifyConnect. We are providing these links only as
        a convenience and are not responsible for the content or links
        displayed on such Websites. Hall Owner and End User both are
        responsible for and assume all risk arising from such use or reliance
        of any third-party Websites.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>TERMINATION AND ACCOUNT CANCELLATION</h2>
      <p className={styles.description}>
        If the Hall Owner and/or the End User breach any of the terms of these
        Terms and Conditions, we have the right to suspend or disable your
        access to or use of the Services. In the event EventifyConnect
        terminates these Terms of Use for your breach, you will remain liable
        for all amounts due hereunder. The End User may cancel your Account at
        any time by sending an email to{" "}
        <a href="mailto:samadhan.ranpise@gmail.com">
          info@EventifyConnect.com
        </a>
        .
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>NO ENDORSEMENT</h2>
      <p className={styles.description}>
        EventifyConnect does not endorse the End User, Hall Owners, or any
        Halls featured on the Services. In addition, we do not attempt to
        confirm, and do not confirm, any End User&apos;s or Hall Owner&apos;s
        purported identity. The End User is responsible for determining the
        identity and suitability of others whom you contact via the Services.
        EventifyConnect will not be responsible for any damage or harm
        resulting from your interactions as a End User with other End Users of
        the Services. By using the Services, you agree that any legal remedy
        or liability that you seek to obtain for actions or omissions of other
        End Users and Hall Owners will be limited to a claim against the
        particular End Users or Hall Owners who caused you harm. You agree not
        to attempt to impose liability on, or seek any legal remedy from
        EventifyConnect in this regard.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>DISCLAIMER</h2>
      <div className={styles.description}>
        <p className={styles.highlight}>
          IF YOU CHOOSE TO USE THE SERVICES, YOU DO SO AT YOUR SOLE RISK. YOU
          ACKNOWLEDGE AND AGREE THAT EVENTIFYCONNECT DOES NOT CONDUCT
          BACKGROUND CHECKS ON ANY HALL OWNER OR END USER. THE HALL OWNER AND
          THE END USER UNDERSTAND AND AGREE THAT THE SERVICES ARE BEING
          PROVIDED TO YOU ON &quot;AS IS&quot; AND ON AN &quot;AS
          AVAILABLE&quot; BASIS. WITHOUT LIMITING THE FOREGOING,
          EVENTIFYCONNECT EXPLICITLY DISCLAIMS ANY WARRANTIES OF
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT
          OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF
          DEALING OR USAGE OF TRADE. EVENTIFYCONNECT MAKES NO WARRANTY THAT
          THE SERVICES OR WEBSITE CONTENT, INCLUDING BUT NOT LIMITED TO, THE
          LISTINGS OR ANY HALL WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON
          AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. EVENTIFYCONNECT MAKES
          NO WARRANTY REGARDING THE QUALITY OF ANY LISTINGS, HALLS, OR ANY
          SERVICES OR WEBSITE CONTENT, OR THE ACCURACY, TIMELINESS,
          TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY WEBSITE CONTENT
          OBTAINED THROUGH THE SERVICES.
        </p>
        <br />
        <p className={styles.highlight}>
          HALL OWNER AND THE END USER ARE SOLELY RESPONSIBLE FOR ALL OF YOUR
          COMMUNICATIONS AND INTERACTIONS WITH OTHER END USERS OF THE SERVICES
          AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A
          RESULT OF YOUR USE OF THE SERVICES, INCLUDING, BUT NOT LIMITED TO,
          ANY HALL OWNERS. THE END USER UNDERSTANDS THAT EVENTIFYCONNECT DOES
          NOT MAKE ANY ATTEMPT TO VERIFY THE STATEMENTS OF END USERS OF THE
          SERVICES OR REVIEW OR VISIT ANY HALLS. EVENTIFYCONNECT MAKES NO
          REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF END USERS OF THE
          SERVICES OR THEIR COMPATIBILITY WITH ANY CURRENT OR FUTURE END USERS
          OF THE SERVICES. BOTH HALL OWNER AND THE END USER AGREE TO TAKE
          REASONABLE PRECAUTIONS IN ALL COMMUNICATIONS AND INTERACTIONS WITH
          EACH OTHER AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR
          INTERACT WITH AS A RESULT OF YOUR USE OF THE SERVICES.
        </p>
      </div>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>INDEMNITY</h2>
      <h3 className={styles['sub-sub-heading']}>As an End User:</h3>
      <p className={styles.description}>
        You agree to indemnify and hold harmless EventifyConnect and its
        officers, directors, employees and agents, from and against any
        claims, disputes, demands, liabilities, damages, losses, and costs and
        expenses, including, without limitation, reasonable legal and
        accounting fees (including costs of defense of litigation by third
        parties), arising out of, or in any way connected with: (a) your
        access to or use of the Services or Website Content or your violation
        of these Terms and Conditions Use; (b) your End User Content; and (c)
        your (i) interaction with any End User or Hall Owner, (ii) scheduling
        a Hall Visit or booking of a Hall or (iii) use of a Hall by you or any
        other End User.
      </p>
      <h3 className={styles['sub-sub-heading']}>As a Hall Owner:</h3>
      <p className={styles.description}>
        You agree to indemnify and hold harmless EventifyConnect and its
        officers, directors, employees and agents, from and against any
        claims, disputes, demands, liabilities, damages, losses, and costs and
        expenses, including, without limitation, reasonable legal and
        accounting fees (including costs of defense of litigation by third
        parties), arising out of, or in any way connected with: (a) your
        access to or use of the Services or Website Content or your violation
        of these Terms and Conditions; (b) your End User Content; and (c) your
        (i) interaction with any End User or Hall Owner, (ii) scheduling a
        Hall Visit or booking of a Hall or (iii) use of a Hall by you or any
        other End User.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>LIMITATION OF LIABILITY</h2>
      <h3 className={styles['sub-sub-heading']}>As an End User:</h3>
      <p className={styles.description}>
        You acknowledge and agree that, to the maximum extent permitted by
        law, the entire risk arising out of your access to and use of the
        services and website content, and your booking of any Halls via the
        services, remains with you. Neither EventifyConnect nor any other
        party involved in creating, producing, or delivering the services or
        website content will be liable for any incidental, special, exemplary
        or consequential damages, including lost profits, loss of data or loss
        of goodwill, service interruption, computer damage or system failure
        or the cost of substitute products or services, or for any damages for
        personal or bodily injury or emotional distress arising out of or in
        connection with these Terms and Conditions, or from the use of or
        inability to use the services or website content, or from any
        communications, interactions or meetings with other End Users of the
        services or other persons with whom you communicate or interact as a
        result of your use of the services, or from your booking of any Hall
        via the services, whether based on warranty, contract, tort (including
        negligence), product liability or any other legal theory, and whether
        or not EventifyConnect has been informed of the possibility of such
        damage, even if a limited remedy set forth herein is found to have
        failed of its essential purpose.
        <br />
        <br />
        In no event will EventifyConnect&apos;s aggregate liability arising
        out of or in connection with these Terms of Use, from your booking of
        any Hall via the services, or from the use of or inability to use the
        services or website content, exceed the amounts you have paid or owe
        for bookings via the services. The limitations of damages set forth
        above are fundamental elements of the basis of the bargain between
        EventifyConnect and you.
      </p>
      <h3 className={styles['sub-sub-heading']}>In respect of a Hall owner:</h3>
      <div className={styles.description}>
        In no event shall EventifyConnect be liable for any direct, indirect,
        incidental, special, incidental, consequential or exemplary damages,
        including but not limited to, damages for loss of profits, goodwill,
        use, data or other intangible losses arising out of or in connection
        with the Website and Payment Facilities, its services or this
        agreement (however arising, including negligence).
        <br />
        <br />
        EventifyConnect&apos;s liability in any circumstance is limited to the
        amount of fees, if any, paid by you to EventifyConnect.
        EventifyConnect, its associates, affiliates and service providers and
        technology partners make no representations or Warranties about the
        accuracy, reliability, completeness, and/or timeliness of any content,
        information, software, text, graphics, links or communications
        provided on or through the use of the Website or that the operation of
        the Website or payment facility will be error free and/or
        uninterrupted. Consequently, EventifyConnect assumes no liability
        whatsoever for any monetary or other damage suffered by you on account
        of:
        <br />
        <ol className={styles.list} style={{ listStyleType: "disc" }}>
          <li>
            The delay, failure, interruption, or corruption of any data or
            other information transmitted in connection with use of the
            Website or payment facilities in any manner
          </li>
          <li>
            Any interruption or errors in the operation of the Website or
            payment facilities.
          </li>
        </ol>
        <br />
        You expressly understand and agree that, EventifyConnect shall not be
        liable for any direct, indirect, incidental, special, consequential or
        exemplary damages, including but not limited to, damages for loss of
        profits, goodwill, use, data or other intangible losses (even if
        EventifyConnect has been advised of the possibility of such damages).
      </div>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>DISPUTE RESOLUTION</h2>
      <h3 className={styles['sub-sub-heading']}>In respect of an End User:</h3>
      <p className={styles.description}>
        In case of any dispute arising out of this Agreement, the Parties
        hereto shall first attempt for an amicable resolution in next 30 days.
        If the parties fail to arrive at any resolution/settlement, then
        either party may invoke the Arbitration for further resolution. The
        Arbitration shall comprise two arbitrators, as appointed by each party
        and a presiding arbitrator who shall be independently appointed by the
        other two arbitrators.
        <br />
        <br />
        The Arbitration proceedings shall take place in Kalyan, Maharastra and
        the same shall be governed by the Arbitration and Conciliation Act,
        1996. The proceedings of the Arbitration shall be conducted in English
        language.
        <br />
        <br />
        The award passed by the Arbitrators shall be final and binding on both
        the Parties and the courts of Kalyan, Maharastra shall have exclusive
        jurisdiction.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>ENTIRE AGREEMENT</h2>
      <p className={styles.description}>
        These Terms of Use constitute the entire and exclusive understanding
        and agreement between EventifyConnect, Hall Owner and End User (as and
        when applicable) regarding the Services and Website Contents, and any
        bookings of Halls made via the Services, and supersede and replace any
        and all prior oral or written understandings or agreements between
        EventifyConnect and you regarding the Services and Website Content.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>ASSIGNMENT</h2>
      <p className={styles.description}>
        You may not assign or transfer these Terms and conditions, by
        operation of law or otherwise, without EventifyConnect&apos;s prior
        written consent. Any attempt by you to assign or transfer these Terms
        and conditions, without such consent, will be null and of no effect.
        EventifyConnect may assign or transfer these Terms of Use, at its sole
        discretion, without restriction. Subject to the foregoing, these Terms
        of Use will bind and inure to the benefit of the parties, their
        successors and permitted assigns.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>NOTICES</h2>
      <p className={styles.description}>
        Any notice or communication by the Hall Owner or the End User may be
        sent to the following address{" "}
        <a href="mailto:samadhan.ranpise@gmail.com">
          info@eventifyconnect.com
        </a>
        .
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>FEEDBACK</h2>
      <p className={styles.description}>
        We welcome feedback, comments and suggestions for improvements to the
        Services (&quot;Feedback&quot;) and Hall Owner and/or the End User can
        submit feedback by emailing us at{" "}
        <a href="mailto:samadhan.ranpise@gmail.com">
          feedback@eventifyconnect.com
        </a>
        . You grant to us a non-exclusive, worldwide, perpetual, irrevocable,
        fully-paid, royalty-free, sub-licensable and transferable license
        under any and all intellectual property rights that you own or control
        to use, copy, modify, create derivative works based upon and otherwise
        exploit the Feedback for any purpose.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>GENERAL</h2>
      <p className={styles.description}>
        The failure of EventifyConnect to enforce any right or provision of
        these Terms of Use will not constitute a waiver of future enforcement
        of that right or provision. The waiver of any such right or provision
        will be effective only if in writing and signed by a duly authorized
        representative of EventifyConnect. Except as expressly set forth in
        these Terms of Use, the exercise by either party of any of its
        remedies under these Terms of Use will be without prejudice to its
        other remedies under these Terms of Use or otherwise. If for any
        reason a court of competent jurisdiction finds any provision of these
        Terms of Use invalid or unenforceable, that provision will be enforced
        to the maximum extent permissible and the other provisions of these
        Terms of Use will remain in full force and effect
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>COMPLIANCE OF LAWS</h2>
      <p className={styles.description}>
        Both the Hall Owner as well as the End User agree to comply with all
        the laws, governing these Terms of Use, whether direct or indirect,
        express or implied.
      </p>
    </div>
    <div className={styles.wrapper}>
      <h2 className={styles['sub-heading']}>CONTACTING EVENTIFYCONNECT</h2>
      <p className={styles.description}>
        If you have any questions about these Terms of Use, please contact us
        at&nbsp;
        <a href="mailto:samadhan.ranpise@gmail.com">
          info@eventifyconnect.com
        </a>
        .
      </p>
    </div>
  </div>
  )
}

export default TermsAndConditionsPage